### CUSTOMMER ##################

### Create customer
POST http://localhost:5000/api/customer
Content-Type: application/json

{
    "name": "Hoà Thanh Tùng",
    "identityNumber": "634984952165",
    "address": "57/5, ấp Hoà Thành, xã Định An, thị trấn An Lộc, Tỉnh Bến Tre"
}

### Read customer
GET http://localhost:5000/api/customer

### Read one customer
GET http://localhost:5000/api/customer/11

### Update customer
PUT http://localhost:5000/api/customer/2
Content-Type: application/json

{
    "name": "Đoàn Thị Thuỷ",
    "identityNumber": "998456321645",
    "address": "54/3, ấp Văn Nghĩa, xã Vĩnh Lộc, huyện Tân Phú, tỉnh Long An"
}

### Delete customer
DELETE  http://localhost:5000/api/customer/1

### Find customer by identity
GET http://localhost:5000/api/customer/find/identity/321698495645


### TYPE SAVNG ##################

### Create type saving
POST http://localhost:5000/api/typesaving
Content-Type: application/json

{
    "name": "12 tháng",
    "termMonth": 12,
    "interestRate": 6,
    "numDayCanWithdraw": 360
}

### Read type saving
GET http://localhost:5000/api/typesaving

### Read one type saving
GET http://localhost:5000/api/typesaving/3

### Update type saving
PUT http://localhost:5000/api/typesaving/2
Content-Type: application/json

{
    "name": "Không kì hạn mới 3",
    "termMonth": 3,
    "interestRate": 5.5,
    "numDayCanWithdraw": 180
}

### Delete type saving
DELETE  http://localhost:5000/api/typesaving/1


### SAVNG ##################

### Create saving
POST http://localhost:5000/api/saving
Content-Type: application/json

{
    "nameCustomer": "Dương Thị Quỳnh",
    "identityNumber": "845699321645",
    "addressCustomer": "54/3, ấp Văn Nghĩa, xã Vĩnh Lộc, huyện Tân Phú, tỉnh Long An",
    "dateCreate": "2022-06-08",
    "money": 1000000,
    "typeSavingId": 2
}

### Read saving
GET http://localhost:5000/api/saving?currentDay=2022-10-01

### Read one saving
GET http://localhost:5000/api/saving/3?currentDay=2022-10-01

### Update saving
PUT http://localhost:5000/api/saving/2
Content-Type: application/json

{
    "nameCustomer": "Dương Thị Nga",
    "identityNumber": "998456321645",
    "addressCustomer": "54/3, ấp Văn Nghĩa, xã Vĩnh Lộc, huyện Tân Phú, tỉnh Long An"
}

### Delete saving
DELETE  http://localhost:5000/api/saving/1

### RULE ##################

### Read rule
GET http://localhost:5000/api/rule

### Read one rule
GET http://localhost:5000/api/rule/minMoneyDeposit

### Update rule
PUT http://localhost:5000/api/rule
Content-Type: application/json

{
    "minMoneyBegin": 1000000,
    "minMoneyDeposit": 100000
}


### DEPOSIT ##################

### Create deposit
POST http://localhost:5000/api/deposit
Content-Type: application/json

{
    "savingId": 2,
    "dateDeposit": "2022-07-11",
    "money": 200000
}


### WITHDRAW ##################

### Create withdraw
POST http://localhost:5000/api/withdraw
Content-Type: application/json

{
    "savingId": 3,
    "dateWithdraw": "2022-09-30",
    "money": 0
}

### REPORT ##################

### Create report
POST http://localhost:5000/api/reportday
Content-Type: application/json

{
    "date": "2022-06-30"
}

### Read report
GET http://localhost:5000/api/reportmonth/2022-06?typeSavingId=1

###
POST http://localhost:5000/api/reportmonth
Content-Type: application/json

{
    "month": "2022-06"
}